---
version: '2'
services:
  db:
    image: influxdb 
    container_name: influxdb
    volumes:
      - "/data/influxdb/:/var/lib/influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - ./env/db.env
  web:
    image: pedrocesarti/internet-speedtest-docker:grafana 
    container_name: speedweb
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
  testing:
    image: pedrocesarti/internet-speedtest-docker:speedtest
    container_name: speedtest
    links:
      - db:db
    env_file:
      - ./env/testing.env
